"""
Project Generator Module

Handles the creation of project structure and files
based on selected templates.

Author: Minhaz Alam
Created: 2026-03
"""

import os


def create_project_structure(project_name: str) -> None:
    """
    Create the complete project structure and initialize base files.
    """
    base_path = os.path.abspath(project_name)

    # Create root directory
    os.makedirs(base_path, exist_ok=True)

    # Create folders
    folders = [
        "airflow/dags",
        "spark/jobs",
        "config",
    ]

    for folder in folders:
        os.makedirs(os.path.join(base_path, folder), exist_ok=True)

    # Generate files
    create_base_files(base_path, project_name)
    create_docker_compose(base_path, project_name)
    create_spark_job(base_path)


def create_base_files(base_path: str, project_name: str) -> None:
    """
    Create README, config, and requirements files.
    """

    # README.md (IMPORTANT: no triple backticks issue)
    readme_content = (
        f"# {project_name}\n\n"
        "Generated by Stackify 🚀\n\n"
        "A production-ready data engineering project scaffold.\n\n"
        "---\n\n"
        "## 🚀 Quickstart\n\n"
        "Run the following command:\n\n"
        "docker-compose up\n\n"
        "Access Spark UI at:\n"
        "http://localhost:8080\n\n"
        "---\n\n"
        "## 📁 Project Structure\n\n"
        "- airflow/dags → Airflow workflows\n"
        "- spark/jobs → Spark batch jobs\n"
        "- config → Configuration files\n\n"
        "---\n\n"
        "## ⚙️ Next Steps\n\n"
        "- Add your Spark job in `spark/jobs`\n"
        "- Extend docker-compose for Airflow/Kafka\n"
    )

    with open(os.path.join(base_path, "README.md"), "w") as f:
        f.write(readme_content)

    # config.yaml
    config_path = os.path.join(base_path, "config", "config.yaml")
    os.makedirs(os.path.dirname(config_path), exist_ok=True)

    config_content = (
        "spark:\n"
        "  master: local[*]\n"
        f"  app_name: \"{project_name}\"\n"
    )

    with open(config_path, "w") as f:
        f.write(config_content)

    # requirements.txt
    with open(os.path.join(base_path, "requirements.txt"), "w") as f:
        f.write("pyspark\n")


def create_docker_compose(base_path: str, project_name: str) -> None:
    """
    Create docker-compose.yml file.
    """

    docker_content = (
        "version: '3.8'\n\n"
        "services:\n"
        "  spark:\n"
        "    image: bitnami/spark:latest\n"
        f"    container_name: {project_name}_spark\n"
        "    environment:\n"
        "      - SPARK_MODE=master\n"
        "    ports:\n"
        "      - \"8080:8080\"\n"
        "      - \"7077:7077\"\n"
        "    volumes:\n"
        "      - ./spark/jobs:/jobs\n"
        "    restart: unless-stopped\n"
    )

    with open(os.path.join(base_path, "docker-compose.yml"), "w") as f:
        f.write(docker_content)


def create_spark_job(base_path: str) -> None:
    """
    Create a sample PySpark job.
    """

    spark_job = (
        "from pyspark.sql import SparkSession\n\n"
        "spark = SparkSession.builder.appName('StackifyJob').getOrCreate()\n\n"
        "data = [('Alice', 25), ('Bob', 30)]\n"
        "df = spark.createDataFrame(data, ['name', 'age'])\n\n"
        "df.show()\n\n"
        "spark.stop()\n"
    )

    job_path = os.path.join(base_path, "spark", "jobs", "batch_job.py")

    with open(job_path, "w") as f:
        f.write(spark_job)