"""
Project Generator Module

Handles the creation of project structure and files
based on selected templates.

Author: Minhaz Alam
Created: 2026-03
"""

import os


def create_project_structure(project_name: str) -> None:
    """
    Create the complete project structure and initialize base files.
    """
    base_path = os.path.abspath(project_name)

    # Create root directory
    os.makedirs(base_path, exist_ok=True)

    # Create folders
    folders = [
        "airflow/dags",
        "spark/jobs",
        "config",
    ]

    for folder in folders:
        os.makedirs(os.path.join(base_path, folder), exist_ok=True)

    # Generate files
    create_base_files(base_path, project_name)
    create_docker_compose(base_path, project_name)
    create_spark_job(base_path)
    create_airflow_dag(base_path, project_name)


def create_base_files(base_path: str, project_name: str) -> None:
    """
    Create README, config, and requirements files.
    """

    # README.md (IMPORTANT: no triple backticks issue)
    readme_content = (
        f"# {project_name}\n\n"
        "Generated by Stackify 🚀\n\n"
        "A production-ready data engineering project scaffold.\n\n"
        "---\n\n"
        "## 🚀 Quickstart\n\n"
        "Run the following command:\n\n"
        "docker-compose up\n\n"
        "Access Spark UI at:\n"
        "http://localhost:8080\n\n"
        "---\n\n"
        "## 📁 Project Structure\n\n"
        "- airflow/dags → Airflow workflows\n"
        "- spark/jobs → Spark batch jobs\n"
        "- config → Configuration files\n\n"
        "---\n\n"
        "## ⚙️ Next Steps\n\n"
        "- Add your Spark job in `spark/jobs`\n"
        "- Extend docker-compose for Airflow/Kafka\n"
    )

    with open(os.path.join(base_path, "README.md"), "w") as f:
        f.write(readme_content)

    # config.yaml
    config_path = os.path.join(base_path, "config", "config.yaml")
    os.makedirs(os.path.dirname(config_path), exist_ok=True)

    config_content = (
        "spark:\n"
        "  master: local[*]\n"
        f"  app_name: \"{project_name}\"\n"
    )

    with open(config_path, "w") as f:
        f.write(config_content)

    # requirements.txt
    with open(os.path.join(base_path, "requirements.txt"), "w") as f:
        f.write("pyspark\n")


def create_docker_compose(base_path: str, project_name: str) -> None:
    """
    Create docker-compose.yml file.
    """

    docker_content = f"""
version: '3.8'

services:
  spark:
    image: bitnami/spark:latest
    container_name: {project_name}_spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./spark/jobs:/opt/airflow/spark/jobs

  airflow:
    image: apache/airflow:2.7.1
    container_name: {project_name}_airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "8081:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./spark/jobs:/opt/airflow/spark/jobs
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin --firstname admin --lastname user --role Admin --email admin@example.com &&
               airflow webserver & airflow scheduler"
"""

    with open(os.path.join(base_path, "docker-compose.yml"), "w") as f:
        f.write(docker_content)


def create_spark_job(base_path: str) -> None:

    """
    Create a sample PySpark job.
    """

    spark_job = (
        "from pyspark.sql import SparkSession\n\n"
        "spark = SparkSession.builder.appName('StackifyJob').getOrCreate()\n\n"
        "data = [('Alice', 25), ('Bob', 30)]\n"
        "df = spark.createDataFrame(data, ['name', 'age'])\n\n"
        "df.show()\n\n"
        "spark.stop()\n"
    )

    job_path = os.path.join(base_path, "spark", "jobs", "batch_job.py")

    with open(job_path, "w") as f:
        f.write(spark_job)

def create_airflow_dag(base_path: str, project_name: str) -> None:
    """
    Create a simple Airflow DAG to run Spark job.

    Args:
        base_path (str): Absolute path of the project
        project_name (str): Project name
    """

    dag_content = f"""from airflow import DAG
from airflow.operators.bash import BashOperator
from datetime import datetime

default_args = {{
    "owner": "stackify",
    "start_date": datetime(2024, 1, 1),
}}

with DAG(
    dag_id="{project_name}_pipeline",
    default_args=default_args,
    schedule_interval="@daily",
    catchup=False,
) as dag:

    run_spark_job = BashOperator(
        task_id="run_spark_job",
        bash_command="python /opt/airflow/spark/jobs/batch_job.py",
    )
"""

    dag_path = os.path.join(base_path, "airflow", "dags", "pipeline_dag.py")

    with open(dag_path, "w") as f:
        f.write(dag_content)